### ISSUE TITLE
Newly created Menues

### ISSUE THREAD

**Issue by tbmuc** [SanderRonde/CustomRightClickMenu#32] opened 2019-03-03 08:57 UTC
Hello Sander,

thank you very much for the new version 2.2.6. Drag & Drag works now almost perfect. However, I found 2 Issues:
1) Can't select newly created menus in oder to move items into them.
2) In some case the menus appears twice. Trying to remove one, removes also the other.

Best
Thomas

**Comment by tbmuc** [comment] 2019-03-03 10:19
There seems to be a workaround: Refreshing the Options page after creating a menu.

**Comment by SanderRonde** [comment] 2019-03-03 11:01
First of all thank you for testing the new version before it even hit browsers, feedback like this is what keeps the extension working.
Now onto the problems, with "can't select newly created menus in order to move items into them" do you mean the "expand menu" button not working, the drag handle not working on the menu itself or it not being possible for items to be dragged into it?
Regarding the second problem, I'm wondering if this is also fixed by reloading the page. I'm also wondering whether you know if this is a menu-only thing or of it happens to other types as well.

I'll be investigating the issue myself as well but if you have more info please let me know. Thanks!

**Comment by tbmuc** [comment] 2019-03-03 11:27
After creating a new menu the "expand menu" arrow is not active. It becomes active when reloading the options page.  

There are also some unexpected effects like duplicate entries when using items without reload. But I can't replicate them in the moment. I will report them if its happen again.

**Comment by SanderRonde** [comment] 2019-03-03 12:22
As you might be able to see I've fixed the first issue but the second one might be a bit harder to nail down. Do you know if this occurs when dragging items around or when just creating them?

**Comment by tbmuc** [comment] 2019-03-03 12:38
If I remember right, it occurred when trying to move a new menu from the bottom to the top. I couldn't do it in one step. At the end there where one menu at th3 bottom and one at the top. I cant replicate it for now, but I will screencast when I make changes at the options. If it occurs again, this will demonstrate it.

**Comment by SanderRonde** [comment] 2019-03-03 12:41
Ah okay that does make sense. I did also manage to recreate it myself even though I was unsure about what exactly caused it when I did it. I then found that dragging something to the top would not actually place it there, probably leading to the double items. With that fixed I can't reproduce the issue anymore so I think it's been fixed. If you get the issue again when the new version releases (2.2.7), please re-open the issue and I'll investigate it again.

**Closed** 2019-03-03 12:42 UTC
